/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "../MCAL/RCC/RCC_Interface.h"
#include "../ECUAL/LED/LED_Interface.h"

#include "../MCAL/GPIO/GPIO_Interface.h"
int main(void)
{
    RCC_init();
    RCC_peripheralEnable(RCC_GPIOA_EN);


    // Initialize GPIO pin PA0 as output
    GPIO_Config_t ledConfig;
    ledConfig.pin.port = PORTA;
    ledConfig.pin.pinNumber = 0;
    ledConfig.mode = GPIO_MODE_OUTPUT_PUSHPULL;
    ledConfig.speed = GPIO_SPEED_2MHZ;

    GPIO_init(&ledConfig);

    while (1) {
        // Toggle PA0
        GPIO_WritePin(&ledConfig.pin, 1);

    }
}
